name: jetwallet_arch_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+2

  # Service locator
  get_it: ^7.2.0
  injectable: ^1.5.3
  provider: ^6.0.3

  # NETWORKING:
  http: ^0.13.4
  dio: ^4.0.6 # http client
  pretty_dio_logger: ^1.1.1 # logger for dio
  signalr_core: ^1.1.1 # ASP.NET Core SignalR Client

  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Build runner
  build_runner: ^2.1.11
  flutter_gen: ^4.2.1
  freezed: ^2.0.3+1

  # Service locator
  injectable_generator: ^1.5.3

  # MobX
  mobx_codegen: ^2.0.7

  # Json
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

flutter:
  generate: true
  uses-material-design: true